### ISSUE TITLE
Installation Problems due to dependency assertive.types no longer available on CRAN 

### ISSUE THREAD

**Issue by tinneuro** [CDCgov/Rnssp#14]
Hi everyone,

Unfortunately I received the error message "dependency 'assertive.types' is not available for package 'Rnssp'" when trying to install your package. On CRAN it says that this package was archived on 2023-10-24 https://cran.r-project.org/web/packages/assertive.types/index.html. Thus one can only get the package running using former available versions of assertive.types. Do you plan to change your code to not depend on this package anymore or any other solution?
Thanks!

**Comment by rosericazondekon** [comment]
Hi @tinneuro 

Thank you for bringing this issue to our attention. The next version of the package will clear out dependencies that are no longer readily available on CRAN. A major version (Rnssp v0.3.0) is in the making and will be released in a couple of months. It will address all dependencies issues and introduce new, interesting features to our users. So please, stay tuned.

Best!

**Comment by tinneuro** [comment]
Dear @rosericazondekon,

thanks a lot for your quick reply! Great then I am looking forward to the next release.

**Comment by rosericazondekon** [comment]
You are welcome @tinneuro. 
We will keep this issue open until the dependency issue with regard to assertive.types is properly and fully addressed.
Thanks!

**Comment by a-roguet** [comment]
Dear @rosericazondekon,
Do you have any rough ETA on the release of the new version? 
Best,

**Comment by rosericazondekon** [comment]
Dear @a-roguet 
Please, expect the new release by late February to early March 2024. It may come sonner in which case, I will update this thread accordingly.

**Comment by a-roguet** [comment]
Thanks for your really prompt answer. 
Thanks, that is good to know. I'll find a way around the time the package is updated. 
Have a great day.

**Comment by a-roguet** [comment]
Note: I could install the Rnssp package using R-4.1.1 after installing assertive.types directly from https://cran.r-project.org/src/contrib/Archive/assertive.types/.

**Comment by rosericazondekon** [comment]
Hi everyone,

We have removed the `assertive.types` dependency and replaced it with `assertions`. Please see [this commit](https://github.com/CDCgov/Rnssp/commit/09c6371ac09558773ffd0d5ab8984e9f361b8463) (and [this one](https://github.com/CDCgov/Rnssp/commit/0f4346ad24cc53827dbea7926f57b9a7bd2bd143)) for more. 

This fix will be part of the upcoming version of the `Rnssp` R package. In the meantime, may install `Rnssp` from its [dev branch](https://github.com/CDCgov/Rnssp/tree/dev). Remember though that the development version is not stable and is prone to changes. 

I am therefore closing this issue since it has been resolved. 

Thank you all for your contributions!

**Comment by rosericazondekon** [comment]
Dear @tinneuro and @a-roguet ,

We just released `Rnssp v0.3.0` which among other features, updates, and bug fixes, resolves the `assertive.types` dependency issue. 

Please, feel free to check the new release note for an exhaustive list of the novelties.

You may install the newly released version by running:
```
devtools::install_github("cdcgov/Rnssp")
```

Thank you!
